version: '3.8'

services:
  app:
    build: .
    container_name: urlshortener_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=urlShortener
      - DB_PORT=5432
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: urlshortener_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: urlShortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: urlshortener_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
